images:
  repository: ghcr.io/arni005/boutique
  tag: "2ea6e1427076a61fa6ceca787272a1d9f298dfd6" # CI overwrites this line
loadGenerator:
  create: false
ingress:
  enabled: true
  host: dev.13.201.104.26.nip.io
# Lower the CPU *requests* so several environments fit on one small node
adService: {resources: {requests: {cpu: 20m}}}
cartService: {resources: {requests: {cpu: 20m}}}
checkoutService: {resources: {requests: {cpu: 20m}}}
currencyService: {resources: {requests: {cpu: 20m}}}
emailService: {resources: {requests: {cpu: 20m}}}
frontend: {externalService: false, resources: {requests: {cpu: 20m}}}
paymentService: {resources: {requests: {cpu: 20m}}}
productCatalogService: {resources: {requests: {cpu: 20m}}}
recommendationService: {resources: {requests: {cpu: 20m}}}
shippingService: {resources: {requests: {cpu: 20m}}}
